Lanelet handler
jkk-research/CooperativeResearchPlatform pull request #14
Opened 2024-09-17 13:36 UTC by AnonymDavid

A package that loads a lanelet2 map from a file and publishes it to a specified topic as binary data.

2024-09-17 13:43 UTC, AnonymDavid commented
Just realized I need to convert the output topics of the driver to match the predefined ones (sensor abstraction inputs).

2024-09-17 14:09 UTC, mesmatyi requested changes

2024-09-17 14:09 UTC, mesmatyi commented on crp_VIL/lanelet_handler/launch/laneletFileLoader.launch.py
would be nice to have an option to set the frame_id, by default it's set to **map** but in some cases could be **map_zala_0**

2024-09-17 14:12 UTC, mesmatyi commented
I feel also the Lanelet2 visualizer package is needed, https://github.com/autowarefoundation/autoware.universe/tree/main/map/map_loader#lanelet2_map_visualization

2024-09-18 08:38 UTC, AnonymDavid commented on crp_VIL/lanelet_handler/launch/laneletFileLoader.launch.py
Done! ([commit](https://github.com/jkk-research/CooperativeResearchPlatform/pull/14/commits/58e0b5847c6ffd836e07879596cd2fb76155ae93))

2024-09-18 09:20 UTC, AnonymDavid commented
> I feel also the Lanelet2 visualizer package is need to be caried over, https://github.com/autowarefoundation/autoware.universe/tree/main/map/map_loader#lanelet2_map_visualization

I added the autoware visualizer to the launcher.

2024-09-18 14:48 UTC, mesmatyi approved these changes

2024-09-20 06:55 UTC, gfigneczi1 approved these changes
from my side it's ok, can be merged

2024-09-20 08:37 UTC, merged