24 crp remove external dependencies
jkk-research/CooperativeResearchPlatform pull request #65
Opened 2024-11-11 07:34 UTC by mesmatyi

Included the *map_loader* package, and the Autoware is no longer an dependeny...

2024-11-11 07:37 UTC, mesmatyi commented
-- altought the package was not able to visualize the motorway, and handling maps maybe, those are considered as invalid maps ?! 
the rest of the maps looked good !

2024-11-11 10:25 UTC, AnonymDavid commented on crp_VIL/lanelet_handler/CMakeLists.txt
> +find_package(visualization_msgs REQUIRED)
visualization_msgs is not used

2024-11-11 11:41 UTC, gfigneczi1 requested changes

2024-11-11 11:41 UTC, gfigneczi1 commented on crp_VIL/mpc_camera_driver
latest is 56e9af, not 9c4de2

2024-11-14 12:15 UTC, gfigneczi1 approved these changes

2024-11-14 12:59 UTC, merged